apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels: 
    project: expense
    app: frontend
    tier: web
spec:
  replicas: 2
  selector: 
    matchLabels:
      project: expense
      app: frontend
      tier: web
  template:
    metadata:
      labels:
        project: expense
        app: frontend
        tier: web
    spec:
      containers:
      - name: frontend
        image: mlndockerhub/frontend:v1

---
apiVersion: v1 
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  # type: LoadBalancer # instead of using ingress resource & ingress controller and Targrt group binding
  selector: 
    project: expense
    tier: web
    app: frontend
  ports:
  - name: frontend-svc-port
    protocol: "TCP"
    port: 80
    targetPort: 80

---
# frontend service attaching to alb target group. no frontend loadbalancer service
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend
  namespace: expense
spec:
  serviceRef:
    name: frontend # route traffic to the awesome-service
    port: 80
  # alb target group
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:529088275803:targetgroup/expense-dev-ingress-alb/60d1d4dd9e7b53bb
  targetType: instance