# ConfigMap with correct env variable names
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
  DB_USER: expense
  DB_PWD: ExpenseApp@1
  DB_DATABASE: transactions

---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    app: backend
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: app
      project: expense
  template:
    metadata:
      labels:
        project: expense
        app: backend
        tier: app
    spec:
      containers:
      - name: backend
        image: mlndockerhub/backend:v1
        envFrom:
        - configMapRef:
            name: backend
        ports:
        - containerPort: 8080

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    app: backend
    tier: app
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080
    targetPort: 8080
