apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
  DB_USER: expense
  DB_PWD: ExpenseApp@1
  DB_DATABASE: transactions

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: api
    project: expense
spec:
  replicas: 1   # keep 1 for stability/debug
  selector:
    matchLabels:
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command:
          - sh
          - -c
          - |
            until nc -z mysql 3306;
            do
              echo "Waiting for MySQL on port 3306...";
              sleep 3;
            done

      containers:
      - name: backend
        image: joindevops/backend:v1
        ports:
        - containerPort: 8080

        envFrom:
        - configMapRef:
            name: backend

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi

        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080
    targetPort: 8080
