apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
  DB_DATABASE: transactions

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: expense
type: Opaque
data:
  DB_USER: ZXhwZW5zZQ==        # base64("expense")
  DB_PWD: RXhwZW5zZUFwcEAx     # base64("ExpenseApp@1")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: app
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: app
        project: expense
    spec:
      containers:
      - name: backend
        image: mlndockerhub/backend:v1
        envFrom:
        - configMapRef:
            name: backend
        - secretRef:
            name: mysql-secret
        ports:
        - containerPort: 8080
